### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ghost** [ScerIO/phar.js#1]
I noticed you had no proper documentation, so I generated some using [TypeDoc](https://typedoc.org/). I thought that this would be helpful for anybody else looking to work with this library. My generated version is hosted at https://phar.surge.sh.

```sh
npx typedoc --out docs/ --ignoreCompilerErrors --excludeProtected --excludePrivate --excludeExternals
```

**Comment by SergeShkurko** [comment]
@nathfreder great idea, thank you

**Comment by SergeShkurko** [comment]
Link to docs added in readme
